"""Initial schema: app + analytics, plus the readonly_analyst role (Sec 4, Layer 1).

The role-level GRANT here is the actual security boundary described in Sec 4 —
it has to hold even if the AST validator / allow-list / limit-injection layers
in app/tools/database_tools.py all have bugs. readonly_analyst gets SELECT on
`analytics.*` and nothing else: no grant on `app.*` means no access to it at all.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-22
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings
from app.db.models import Base

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")

    # Baseline migration: build every app/analytics table straight from the
    # ORM metadata. Future schema changes should be autogenerated diffs
    # against this.
    #
    # Explicitly scoped to app.*/analytics.* — Base.metadata.create_all(bind=bind)
    # with no `tables=` filter would also pick up whatever ELSE happens to be
    # registered on the shared Base.metadata by the time this runs, which
    # includes olist.* (app/db/db_models_olist.py is imported unconditionally
    # by app/db/migrations/env.py so migration 0002 can reach it). On a
    # database migrated from scratch with today's codebase, that made this
    # migration try to create olist.customers before migration
    # 0002_olist_schema has created the olist schema at all — a real defect
    # found running the full 0001->0004 chain against a fresh database
    # (Phase 14 migration audit), invisible on any database that was
    # migrated incrementally, as every existing deployment's DB was.
    # 0002_olist_schema already scopes its own create_all the same way.
    bind = op.get_bind()
    own_tables = [
        table for name, table in Base.metadata.tables.items()
        if name.startswith("app.") or name.startswith("analytics.")
    ]
    Base.metadata.create_all(bind=bind, tables=own_tables)

    settings = get_settings()
    db_name = bind.engine.url.database

    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'readonly_analyst') THEN
                CREATE ROLE readonly_analyst LOGIN PASSWORD '{settings.readonly_db_password}';
            END IF;
        END
        $$;
        """
    )
    op.execute(f'GRANT CONNECT ON DATABASE "{db_name}" TO readonly_analyst')
    op.execute("GRANT USAGE ON SCHEMA analytics TO readonly_analyst")
    op.execute("GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO readonly_analyst")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO readonly_analyst"
    )
    # No grants at all on `app` schema for readonly_analyst — absence of a grant
    # is the enforcement; Postgres default-denies cross-schema access.


def downgrade() -> None:
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics FROM readonly_analyst")
    op.execute("DROP OWNED BY readonly_analyst")
    op.execute("DROP ROLE IF EXISTS readonly_analyst")
    op.execute("DROP SCHEMA IF EXISTS analytics CASCADE")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE")
